export const metadata = {
  title: "Our Services - AI-Powered Enterprise Solutions & Automation | ReKnew",
  description: "Explore ReKnew's comprehensive AI-powered enterprise solutions. From intelligent automation to data analytics, cloud solutions, and compliance management - discover how we transform businesses through cutting-edge technology.",
  keywords: [
    "AI enterprise solutions",
    "intelligent automation services", 
    "business process automation",
    "enterprise AI transformation",
    "cloud solutions",
    "data analytics",
    "compliance management",
    "generative AI services",
    "digital transformation",
    "workflow optimization",
    "AI consulting services",
    "enterprise software development"
  ],
  authors: [{ name: "ReKnew Team" }],
  creator: "ReKnew",
  publisher: "ReKnew",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: "Our Services - AI-Powered Enterprise Solutions & Automation | ReKnew",
    description: "Transform your business with ReKnew's AI-powered solutions. Intelligent automation, data analytics, cloud solutions, and compliance management - all designed to optimize your enterprise operations.",
    url: "https://reknew.ai/ourservices",
    siteName: "ReKnew",
    type: "website",
    locale: "en_US",
    images: [
      {
        url: "https://reknew.ai/assets/reknew-logo-white.png",
        width: 1200,
        height: 630,
        alt: "ReKnew - Enterprise AI Solutions & Services",
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@ReKnewAI",
    creator: "@ReKnewAI",
    title: "Our Services - AI-Powered Enterprise Solutions | ReKnew",
    description: "Discover ReKnew's comprehensive AI solutions: intelligent automation, data analytics, cloud services, and compliance management for enterprise transformation.",
    images: ["https://reknew.ai/assets/reknew-logo-white.png"],
  },
  alternates: {
    canonical: "https://reknew.ai/ourservices",
    languages: {
      "en-US": "https://reknew.ai/ourservices",
    },
  },
  category: "Services",
  classification: "Business Services",
  applicationName: "ReKnew",
  referrer: "origin-when-cross-origin",
};
